export const FETCH_HOUSES_REQUEST = 'FETCH_HOUSES_REQUEST';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const FETCH_HOUSES_FAILURE = 'FETCH_HOUSES_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
