export const FETCH_HOUSES_REQUEST = 'FETCH_HOUSES_REQUEST';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const FETCH_HOUSES_FAILURE = 'FETCH_HOUSES_FAILURE';

export const FETCH_HOUSE_REQUEST = 'FETCH_HOUSE_REQUEST';
export const FETCH_HOUSE_SUCCESS = 'FETCH_HOUSE_SUCCESS';
export const FETCH_HOUSE_FAILURE = 'FETCH_HOUSE_FAILURE';

export const LOGIN = 'LOGIN';
