export const FETCH_HOUSES_REQUEST = 'FETCH_HOUSES_REQUEST';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';
export const FETCH_HOUSES_FAILURE = 'FETCH_HOUSES_FAILURE';

export const FETCH_HOUSE_REQUEST = 'FETCH_HOUSE_REQUEST';
export const FETCH_HOUSE_SUCCESS = 'FETCH_HOUSE_SUCCESS';
export const FETCH_HOUSE_FAILURE = 'FETCH_HOUSE_FAILURE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const ADD_FAVORITE_SUCCESS = ' ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAILURE = '  ADD_FAVORITE_FAILURE';

export const FETCH_FAVORITE_REQUEST = ' FETCH_FAVORITE_REQUEST';
export const FETCH_FAVORITE_SUCCESS = ' FETCH_FAVORITE_SUCCESS';
export const FETCH_FAVORITE_FAILURE = '  FETCH_FAVORITE_FAILURE';
